version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: vestasys-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vestasys}
      MYSQL_USER: ${MYSQL_USER:-vestasysuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-vestasyspassword}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vestasys-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vestasys-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "8080:80"
    networks:
      - vestasys-network
    profiles:
      - dev

networks:
  vestasys-network:
    driver: bridge

volumes:
  mysql_data:
